global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "prometheus.rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9100']
        labels:
          group: 'node_exporter'
